#
# Script de construccion (SCons)
#
import os

plataforma = ARGUMENTS.get('OS', Platform())
env = Environment(CPPPATH = ['src/robot', 'src/red_neuronal', 'src/libpipeline', 'src/filtro_gestos', 'src/ventana_imagen'], ENV = os.environ, platform = plataforma, PLATFORM=plataforma, LIBPATH='lib')

if str(plataforma) == str('win32'):
    env.Append(CC='gcc -mms-bitfields', tools=['mingw'], LINKFLAGS='--export-dynamic')

env.ParseConfig('pkg-config glib-2.0 --cflags --libs')
env.ParseConfig('pkg-config libglade-2.0 --cflags --libs')

print "-- Compilando para", plataforma, "--"

if ARGUMENTS.get('release', 0):
    print ('-- Release --')
    env.Append(DEBUG=0)
else:
    print ('-- Debug --')
    env.Append(DEBUG=1)

# Libpipeline
env.Library('lib/pipeline', 'src/libpipeline/pipeline.c')
env.Install('bin', ['src/libpipeline/pipeline.dtd'])

# Gestion
env.SharedLibrary('bin/gestion', 'src/gestion/gestion.c')

# Filtro gestos
fil = env.Copy()
fil.Append(LIBS=['lua', 'lualib'])
fil.SharedLibrary('bin/filtro_gestos', 'src/filtro_gestos/filtro_gestos.c')
env.Install('bin', ['src/filtro_gestos/filtro.lua'])

# Salida
env.SharedLibrary('bin/salida', 'src/salida/salida.c')
env.Install('bin', ['src/salida/ventana_salida.glade'])

# La ventana de imagenes
img = env.Copy()
img.Append(LIBS=['sane'])
img.ParseConfig('pkg-config libxine --cflags --libs')
img.SharedLibrary('bin/ventana_imagen', 'src/ventana_imagen/ventana_imagen.c')
env.Install('bin', ['src/ventana_imagen/ventana_imagen.glade'])

# El ejecutable
pip = env.Copy()
pip.Prepend(LIBS=['pipeline'])
#pip.Append(LINKFLAGS='-mms-bitfields')
pip.Program('bin/pipeline', 'src/pipeline/main.c')
env.Install('bin', ['src/pipeline/ventana_pipeline.glade'])
env.Install('bin', ['src/pipeline/vision.xml'])

# Imagenes o camara, segun sea Linux o Windows
if str(plataforma) == str('posix'):
    env.SharedLibrary('bin/imagenes', 'src/imagenes/imagenes.c')
else:
    cam = env.Copy()
    cam.Append(LIBS=['strmiids', 'uuid', 'oleaut32', 'ole32', 'quartz', 'user32'])
    cam.SharedLibrary('bin/camara', ['src/camara/camara.cpp', 'src/camara/Captura.cpp'])


# Ocr
env.SharedLibrary('bin/ocr', ['src/ocr/ocr.c', 'src/ocr/ocr_code.c'])
env.Install('bin', ['src/ocr/base_datos'])

# Post gestion
env.SharedLibrary('bin/post_gestion', 'src/post_gestion/post_gestion.c')

# Red neuronal
env.SharedLibrary('bin/red_neuronal', ['src/red_neuronal/red.c', 'src/red_neuronal/red_neuronal.c'])
env.Install('bin', ['src/red_neuronal/orden_net'])

# Robot
rob = env.Copy()
if str(plataforma) == str('posix'):
    rob.Append(LIBS=['lua', 'lualib', 'parapin'])
else:
    rob.Append(LIBS=['lua', 'lualib'])
    
rob.SharedLibrary('bin/robot', 'src/robot/robot.c')
env.Install('bin', ['src/robot/robot.lua'])

# Ventana parametros
env.SharedLibrary('bin/ventana_parametros', 'src/ventana_parametros/ventana_parametros.c')
env.Install('bin', ['src/ventana_parametros/ventana_parametros.glade'])

# Documentacion
if str(plataforma) == str('posix'):
    env.PostScript('bin/vision', 'doc/vision.tex')
